/**
 * PostPreviewController constructor.
 * @constructor
 * @param {!angular.scope} $scope Angular's scope object.
 */
var PostPreviewController = function($scope, UserService) {
  /** @export */
  this.scope_ = $scope;
  /** @export */
  this.post_ = this.scope_.post;
  /** @export */
  this.currentUser_ = UserService.getCurrentUser();
};

/**
 * Removes current post.
 * @param {!Object} event Event generated by the browser.
 */
PostPreviewController.prototype.removePost = function(event){
  this.scope_.$emit("removePost",this.post_);
  event.stopImmediatePropagation();
}