/**
 * PostPreviewController constructor.
 * @constructor
 * @param {!angular.scope} $scope Angular's scope object.
 */
var PostPreviewController = function($scope){
  /** @export */
  this.scope_ = $scope;
  /** @export */
  this.post_ = null;
  /** @export */
  this.currentUser_ = null;

  this.scope_.$watch('post',function(){
  	this.post_ = this.scope_.post;
  }.bind(this));

  this.scope_.$watch('currentUser',function(){
  	this.currentUser_ = this.scope_.currentUser;
  }.bind(this));
};

/**
 * Removes current post.
 * @param {!Object} event Event generated by the browser.
 */
PostPreviewController.prototype.removePost = function(event){
  this.scope_.$emit("removePost",this.post_);
  event.stopImmediatePropagation();
}