/**
 * PostPreviewController constructor.
 * @constructor
 * @param {!angular.scope} $scope Angular's scope object.
 * @param {Function} UserService Service which provides current user.
 */
var PostPreviewController = function($scope, UserService) {
  /** @private {angular.scope} */
  this.scope_ = $scope;

  /** @export {Object} */
  this.post = this.scope_.post;
  /** @export {Object} */
  this.currentUser = UserService.getCurrentUser();
};

/**
 * Removes current post.
 * @param {!Object} event Event generated by the browser.
 */
PostPreviewController.prototype.removePost = function(event) {
  this.scope_.$emit("removePost", this.post);
  event.stopImmediatePropagation();
}